version: '3.7'
services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "3001:3001"
      - "3003:3003"
    environment:
      NODE_ENV: development
    volumes:
      - ${DATA}/log/node:/var/log/node
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
